- .gitignore
- fitpay/src/main/java/com/fitpay/android/webview/WebViewCommunicator.java
created  com.fitpay.android.webview package with a WebViewCommunicator interface to be implemented by the WebViewCommunicatorImpl in the SDK.
> Added WebViewCommunicator Interface to the project

- build.gradle
- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/utils/ApiManager.java
- fitpay/src/main/java/com/fitpay/android/utils/Constants.java
- fitpay/src/main/java/com/fitpay/android/utils/FitPayClient.java
- fitpay/src/main/java/com/fitpay/android/utils/FitPayService.java
- fitpay/src/main/java/com/fitpay/android/utils/RTMSession.java
- fitpay/src/test/java/com/fitpay/android/CommitTest.java
- fitpay/src/test/java/com/fitpay/android/CreditCardTest.java
- fitpay/src/test/java/com/fitpay/android/DeviceTest.java
- fitpay/src/test/java/com/fitpay/android/Steps.java
- fitpay/src/test/java/com/fitpay/android/TestConstants.java
- fitpay/src/test/java/com/fitpay/android/UserTest.java
- gradle/wrapper/gradle-wrapper.properties
add support for configuration of base fitpay url, remove hard coded url references, remove tests for previousCommit - feature is no longer supported, ignore tests that fail - will re-enable as they are debugged
> Plat 1096 explore the sdk

- fitpay/src/main/java/com/fitpay/android/webview/WebViewCommunicator.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/AckResponseModel.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/WebViewCommunicatorStubImpl.java
Modified WebViewCommunicator interface to correspond to the latest developments on the webview side in terms of the RTM refactoring. Added stub implementation of the interface.
@bpwalford @tgshanahan @ssteveli
> modified WebViewCommunicator, added stub implementation

- fitpay/src/main/java/com/fitpay/android/webview/impl/WebViewCommunicatorStubImpl.java
added JavascriptInterface annotation to web view communicator stub
@ssteveli @bpwalford @tgshanahan
> added JavascriptInterface annotation to web view communicator stub

- fitpay/build.gradle
added uploadArchives task so the aar library can be locally deployed during pagare app development cycle.
@tgshanahan @bpwalford
> added uploadArchives task

- fitpay/src/main/java/com/fitpay/android/webview/impl/SyncResponseModel.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/WebViewCommunicatorStubImpl.java
refactored web view communicator impl, added model for sync response
> refactored web view communicator impl, added model for sync response

- fitpay/src/main/java/com/fitpay/android/api/ApiManager.java
- fitpay/src/main/java/com/fitpay/android/api/models/card/Address.java
- fitpay/src/main/java/com/fitpay/android/api/models/card/CreditCard.java
- fitpay/src/main/java/com/fitpay/android/api/models/device/Commit.java
- fitpay/src/main/java/com/fitpay/android/api/models/device/CommitModel.java
- fitpay/src/main/java/com/fitpay/android/api/models/device/Device.java
- fitpay/src/main/java/com/fitpay/android/api/models/user/LoginIdentity.java
- fitpay/src/main/java/com/fitpay/android/api/models/user/User.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/CommitHandler.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/DeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/callbacks/IListeners.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/enums/Sync.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/events/CommitFailed.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/events/CommitSuccess.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/ble/BluetoothPaymentDeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/ble/GattDeviceCharacteristicsOperation.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/mock/MockPaymentDeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/interfaces/IPaymentDeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/model/PaymentDeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/utils/DevicePreferenceData.java
- fitpay/src/test/java/com/fitpay/android/Steps.java
- fitpay/src/test/java/com/fitpay/android/TestActions.java
- fitpay/src/test/java/com/fitpay/android/UserTest2.java
- fitpay/src/test/java/com/fitpay/android/paymentdevice/PaymentDeviceTest.java
Add support for all commit types
removed previous commit
configure payment service via shared preferences
> Plat 1225 add support for card add commit

- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/paymentdevice/DeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/ble/GattSetNotificationOperation.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/mock/MockPaymentDeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/pagare/PebbleDeviceInfo.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/pagare/PebblePagarePaymentServiceDevice.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/interfaces/IPaymentDeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/model/PaymentDeviceService.java
- fitpay/src/main/java/com/fitpay/android/utils/ModelAdapter.java
fixed defect on commit payload deserialization - now types based on payload 'key' field
finished out Mock device wallet functions as provided by commits
> added support for pebble pagare

- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/webview/WebViewCommunicator.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/WebViewCommunicatorStubImpl.java
refactoring to support pebble-web ui
> refactoring to support pebble-web ui

- fitpay/src/main/java/com/fitpay/android/webview/impl/WebViewCommunicatorStubImpl.java
replaced response value to correspond to rtm expectations
@tgshanahan
> replaced response value to correspond to rtm expectations

- .travis.yml
Tests were not running in travis
> turn tests back on

- build.gradle
- fitpay/build.gradle
- local.properties
> Plat 1181 simplify bintray push

- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/api/models/device/Device.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/DeviceService.java
- fitpay/src/test/java/com/fitpay/android/NotificationsTest.java
This release addressed commit retrieval bug discovered when reviewing the SDK code.
> Merge pre-rel 0411 branch into Master

- .travis.yml
- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/api/models/device/Device.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/DeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/PaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/mock/MockPaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/utils/RxBus.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/WebViewCommunicatorImpl.java
- fitpay/src/test/java/com/fitpay/android/CreditCardTest.java
- fitpay/src/test/java/com/fitpay/android/CreditCardTest2.java
- fitpay/src/test/java/com/fitpay/android/Steps.java
- fitpay/src/test/java/com/fitpay/android/TestActions.java
- fitpay/src/test/java/com/fitpay/android/TestConstants.java
fixes with device sync.
fixes in tests
> Pgr 991 mock device

- .travis.yml
- README.md
- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/paymentdevice/DeviceService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/PaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/ble/BluetoothPaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/mock/MockPaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/interfaces/IPaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/utils/NotificationManager.java
- fitpay/src/main/java/com/fitpay/android/webview/WebViewCommunicator.java
- fitpay/src/main/java/com/fitpay/android/webview/events/RtmMessage.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/AppResponseModel.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/WebViewCommunicatorImpl.java
- fitpay/src/main/java/com/fitpay/android/webview/models/RtmVersion.java
updates in Readme file, comments
Deprecated methods were removed. Refactoring after removing deprecated methods
> Pgr 1068 readme

- fitpay/src/main/java/com/fitpay/android/webview/models/WvConfig.java
"accountExist" -> "account"
"email" -> "userEmail"
> wvconfig key names fix

- .travis.yml
- build.gradle
- fitpay/build.gradle
- gradle/wrapper/gradle-wrapper.properties
gradle plugin 3.x, remove retrolambda, compileSdkVersion 27.x
check Android_WV app for updates: https://github.com/fitpay/Pagare_Android_WV/commit/0713eb59f36cb428f7b02c7f7c40149e41f9aa4b
> updates for AndroidStudio 3.x

- fitpay/src/main/java/com/fitpay/android/api/models/device/CreditCardCommit.java
fake credit card contains pan, cvv inside payload, but other cards has additional encryptedData with these values
> changes CreditCardCommit model 

- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/utils/KeysManager.java
You should manually add Bouncycastle into Pagare app. https://github.com/fitpay/Pagare_Android_WV/commit/25f6546708a3e99880fe8ab0d398df20d8eb43fc
> use bouncycastle in tests only

- .travis.yml
- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/api/ApiManager.java
- fitpay/src/main/java/com/fitpay/android/utils/KeysManager.java
- fitpay/src/main/java/com/fitpay/android/utils/SecurityProvider.java
- fitpay/src/test/java/com/fitpay/android/Steps.java
- fitpay/src/test/java/com/fitpay/android/TestActions.java
example how to use: https://github.com/fitpay/Pagare_Android_WV/commit/e5a53922e40a53189d57b99b247d51fc707af8da
> Plat 4330 Make Bouncycastle optional

- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/paymentdevice/DeviceSyncManager.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/PaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/models/SyncProcess.java
- fitpay/src/test/java/com/fitpay/android/CommitTest2.java
continue processing commits even if some has been expired
> sdk:0.4.40. continue commits processing

- fitpay/src/main/java/com/fitpay/android/api/models/device/PaymentDevice.java
I believe this is all that is needed in order to make the initialization state available since it's already in the JSON
> adding state

- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/api/models/card/CreditCard.java
- fitpay/src/main/java/com/fitpay/android/api/models/user/User.java
- fitpay/src/main/java/com/fitpay/android/utils/StringUtils.java
- allows older phones to encrypt correctly
> Adding encryptor provider BouncyCastle

- build.gradle
- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/a2averification/A2AIssuerResponse.java
- fitpay/src/main/java/com/fitpay/android/a2averification/A2AVerificationError.java
- fitpay/src/main/java/com/fitpay/android/utils/Constants.java
- added getResponse() so the OEM can check response and vary accordingly
> A2A increased error types plat 4800

- fitpay/src/main/java/com/fitpay/android/api/ApiManager.java
- fitpay/src/main/java/com/fitpay/android/api/services/AuthClient.java
- fitpay/src/test/java/com/fitpay/android/Steps.java
- fitpay/src/test/java/com/fitpay/android/TestActions.java
- fitpay/src/test/java/com/fitpay/android/UserTest2.java
- rename loginUser to login
- adding endpoint to AuthClient
> Adding login with firebaseToken

- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/api/ApiManager.java
- fitpay/src/main/java/com/fitpay/android/api/services/FitPayService.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/DeviceSyncManager.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/constants/ApduConstants.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/PaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/ble/BluetoothPaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/mock/MockPaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/interfaces/PaymentDeviceConnectable.java
- fitpay/src/test/java/com/fitpay/android/TestActions.java
- fitpay/src/test/java/com/fitpay/android/paymentdevice/impl/MockPaymentDeviceTest.java
- remove tow functions off of PaymentDeviceConnectors
- updated to some lamdas
> Mock Payment Connector now uses the boarding script.

- fitpay/src/main/java/com/fitpay/android/paymentdevice/DeviceSyncManager.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/mock/MockPaymentDeviceConnector.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/utils/sync/SyncThreadExecutor.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/utils/sync/SyncWorkerTask.java
payment connector uses its own thread for syncing
> deviceSyncManager: allocate max 2 thread pools

- fitpay/src/main/java/com/fitpay/android/api/models/PlatformConfig.java
- fitpay/src/main/java/com/fitpay/android/api/services/FitPayClient.java
- fitpay/src/main/java/com/fitpay/android/api/services/FitPayService.java
- looks like it is pulling from the correct key already.
> Update config url

- fitpay/src/main/java/com/fitpay/android/paymentdevice/models/SyncProcess.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/utils/sync/SyncThreadExecutor.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/utils/sync/SyncWorkerTask.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/WebViewCommunicatorImpl.java
don't sync if syncInfo.deviceId and connector.device.deviceId are not the same (rarely reproducible from push notification with two connectors)
> start sync after event. 

- fitpay/src/main/java/com/fitpay/android/api/models/BaseModel.java
- fitpay/src/main/java/com/fitpay/android/api/models/card/CreditCardModel.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/DeviceSyncManager.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/models/SyncInfo.java
- fitpay/src/main/java/com/fitpay/android/rtm/callbacks/RTMListener.java
- fitpay/src/main/java/com/fitpay/android/rtm/enums/ErrorCodes.java
- fitpay/src/main/java/com/fitpay/android/rtm/models/WebViewSessionData.java
- update sendAckSync function
- bump deprecation numbers from 1.0.3 to 1.1.0 since that will be the next release
- removing makePutCall because it is unused
> Update SyncInfo model

- fitpay/src/main/java/com/fitpay/android/configs/WvPaymentDeviceInfo.java
- fitpay/src/main/java/com/fitpay/android/configs/WvPaymentDeviceInfoSecure.java
- removed public functions that weren't being used in the sdk because they are in a non-public class.
> Add profileId to WvPaymentDeviceInfo

- fitpay/src/main/java/com/fitpay/android/api/ApiManager.java
- fitpay/src/main/java/com/fitpay/android/api/callbacks/ApiCallbackExt.java
- fitpay/src/main/java/com/fitpay/android/api/models/ImageAssetWithOptionsReference.java
- fitpay/src/main/java/com/fitpay/android/api/models/apdu/ApduPackage.java
- fitpay/src/main/java/com/fitpay/android/api/models/security/ECCKeyPair.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/ble/GattApduComplexOperation.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/ble/GattManager.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/ble/GattSetIndicationOperation.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/impl/ble/message/ContinuationControlBeginMessage.java
- fitpay/src/main/java/com/fitpay/android/paymentdevice/utils/sync/SyncWorkerTask.java
- fitpay/src/main/java/com/fitpay/android/utils/EventCallback.java
- fitpay/src/main/java/com/fitpay/android/utils/KeysManager.java
- fitpay/src/main/java/com/fitpay/android/utils/StringUtils.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/parser/RtmParserV3.java
- fitpay/src/main/java/com/fitpay/android/webview/impl/webclients/FitpayWebChromeClient.java
- removing = null
- removing unused imports
- removing functions that did nothing
> lint check improvements

- build.gradle
- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/api/models/BaseModel.java
- fitpay/src/main/java/com/fitpay/android/api/models/Link.kt
- fitpay/src/main/java/com/fitpay/android/api/models/Links.java
- fitpay/src/main/java/com/fitpay/android/api/models/card/CreditCard.java
- fitpay/src/main/java/com/fitpay/android/api/models/user/User.java
- fitpay/src/main/java/com/fitpay/android/api/sse/UserEventStream.java
- fitpay/src/main/java/com/fitpay/android/configs/FitpayWeb.java
- fitpay/src/main/java/com/fitpay/android/utils/ModelAdapter.java
- adding Link Model
- adding Kotlin
- adding getWebappCardLink, getEventStreamLink, getWebappWalletLink
- deprecated a few functions
> Plat 5535 templated Links

- fitpay/src/main/java/com/fitpay/android/api/enums/ProvisioningFailedReasons.java
- fitpay/src/main/java/com/fitpay/android/api/models/Payload.java
- fitpay/src/main/java/com/fitpay/android/api/models/card/CreditCard.java
- fitpay/src/main/java/com/fitpay/android/api/models/device/CreditCardCommit.java
Tested manually - no framework for unit testing CreditCardCommit parsing yet + additional cleanup needed with V2 changes
> Added ProvisioningFailedReasons

- fitpay/src/main/java/com/fitpay/android/api/ApiManager.java
- fitpay/src/main/java/com/fitpay/android/api/models/BaseModel.java
- fitpay/src/main/java/com/fitpay/android/api/models/Transaction.java
- fitpay/src/main/java/com/fitpay/android/api/models/card/CreditCard.java
- fitpay/src/main/java/com/fitpay/android/api/models/card/CreditCardModel.java
- fitpay/src/main/java/com/fitpay/android/api/models/device/CommitModel.java
- fitpay/src/main/java/com/fitpay/android/api/models/device/CreditCardCommit.java
- fitpay/src/main/java/com/fitpay/android/api/services/AuthService.java
- fitpay/src/main/java/com/fitpay/android/api/services/BaseClient.java
- fitpay/src/main/java/com/fitpay/android/api/services/FitPayClient.java
- fitpay/src/main/java/com/fitpay/android/api/services/FitPayService.java
- fitpay/src/main/java/com/fitpay/android/api/services/UserService.java
- fitpay/src/main/java/com/fitpay/android/utils/Constants.java
- fitpay/src/main/java/com/fitpay/android/utils/ModelAdapter.java
- fitpay/src/test/java/com/fitpay/android/Steps.java
Adding EncryptedTransaction to Transaction model and updated getters
- Update CreditCardCommit / It doesn't have encryptedData
- Remove unused DeviceSerializer
- create a v2 call path and
- pass through the v2 accept header
- don't override accept header if passed through
- Add getAuthorizationStatus to transaction test to confirm encrypted parsing is still working
- cleaned up Steps test file
> Plat 5643 encrypted transaction

- fitpay/src/main/java/com/fitpay/android/a2averification/A2AVerificationRequest.java
- fitpay/src/test/java/com/fitpay/android/BaseTestActions.java
- fitpay/src/test/java/com/fitpay/android/a2averification/A2AVerificationTest.java
> add creditCardId and verificationId data to A2AVerificationRequest

- build.gradle
- fitpay/build.gradle
- fitpay/src/main/java/com/fitpay/android/api/models/Link.kt
- fitpay/src/main/java/com/fitpay/android/utils/RxBus.java
- gradle/wrapper/gradle-wrapper.properties
Update build.gradle dependencies.
Remove RxJava1.x
> Deps update

- build.gradle
- fitpay/src/main/java/com/fitpay/android/configs/FitpayConfig.java
- fitpay/src/main/java/com/fitpay/android/configs/FitpayConfigWebModel.java
- fitpay/src/main/java/com/fitpay/android/configs/FitpayWeb.java
- fitpay/src/main/java/com/fitpay/android/configs/WvConfig.java
- fitpay/src/test/java/com/fitpay/android/configs/FitpayWebTest.java
- fitpay/src/test/resources/fitpay_config.json
add language to webview config automatically
> Plat 5898 language

- fitpay/src/main/java/com/fitpay/android/api/models/device/CreditCardCommit.java
updated the getter to always return null.  CVV should never get returned to the client.
> do not return the cvv in any form to the client

- fitpay/src/main/java/com/fitpay/android/webview/impl/webclients/FitpayWebClient.java
* handle mail action.
Issue: CA-77428
> gcm not handling email support from card details
